# Generated by Django 5.1.5 on 2025-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkyard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_name',
            field=models.CharField(default='', max_length=355),
            preserve_default=False,
        ),
    ]
