# Generated by Django 5.1.5 on 2025-02-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junkyard_app', '0002_product_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_name',
        ),
    ]
