# Generated by Django 5.1.5 on 2025-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkyard_app', '0003_remove_product_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
