# Generated by Django 5.1.4 on 2025-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkyard_app', '0005_product_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=21)),
                ('email', models.CharField(max_length=400)),
            ],
        ),
    ]
