# Generated by Django 5.1.5 on 2025-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkyard_app', '0006_kontakt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kontakt',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=100.0, max_length=200),
            preserve_default=False,
        ),
    ]
